### ISSUE TITLE
QR extraction a hit-or-miss for IT green pass

### ISSUE THREAD

**Issue by edo0** [michaeltroger/greenpass-android#55] opened 2021-12-06 08:36 UTC
Most likely the issue is similar to that of the NZ pass (QR code being too small). In my experience, only 1 out of 3 passes I tested over the past year had the QR code correctly identified and rendered — the others would just not be detected.

This is party alleviated by using the QR-code-only version of the pass, but it would be great if it could be fixed with the integral pass (sample below)

![Screenshot_20211206-093155_Gallery_1](https://user-images.githubusercontent.com/16632292/144813672-c3c11346-538c-4cee-a6a7-cfc4bf5373e5.png)

**Comment by michaeltroger** [comment] 2021-12-07 18:24
Hi!
I'm not sure how to interpret the sample image.
Is it multi page document? Is the QR code on the first page?
So far the app only searches for an QR code on the document's first page

**Comment by edo0** [comment] 2021-12-07 22:58
My apologies, it's surprisingly hard to find a proper sample image in good resolution for the Italian green pass.
It's unfortunately a one-page PDF file, meant for printing on a regular A4 sheet of paper and folded in 4 parts for convenience.  
Therefore, I believe the code may "appear" as too small for extraction by the app.

![image](https://user-images.githubusercontent.com/16632292/145118602-94b3935d-69b0-467d-96a7-67d0103a0000.png)

**Comment by michaeltroger** [comment] 2021-12-07 23:18
Ok THX I see. Yes, it's most likely size related.

**Comment by michaeltroger** [comment] 2022-03-05 14:54
Duplicate of https://github.com/michaeltroger/greenpass-android/issues/54

**Closed** 2022-03-05 14:53 UTC
Labels: bug
