### ISSUE TITLE
[ENHANCEMENT] Support multiple barcodes on a single page

### ISSUE THREAD

**Issue by samolukadjo** [michaeltroger/greenpass-android#273] opened 2024-07-23 21:47 UTC
**Is your feature request related to a problem? Please describe.**
When a document includes multiple qr/other codes on one page only one is detected and extracted above. This is problem when, for example, a ticket contains a separate code for the ticket and the return ticket.

**Describe the solution you'd like**
The user should be able to select the codes in the page they'd like to show up above it.

**Describe alternatives you've considered**
The app should detect all the codes in a page that it can and show them one after another above the page, preferably in order they appear on the page.

**Additional context**
N/A

**Comment by michaeltroger** [comment] 2024-10-13 18:43
Duplicate of https://github.com/michaeltroger/greenpass-android/issues/274

**Closed by michaeltroger** 2024-10-13 18:43 UTC
Labels: duplicate, enhancement
